import React from 'react';
import { StyleSheet } from 'react-native';
import { Section, Block } from 'react-native-responsive-layout';
import FastImage from '@cuvent/react-native-fast-image';
import { useSafeAreaFrame } from 'react-native-safe-area-context';
import * as Linking from 'expo-linking';

import PageLayout from '../../components/PageLayout';
import { PageText } from '../../components/Text';
import HeaderRow from '../../components/HeaderRow';

import SocialMedia from './SocialMedia';

const About = () => (
  <PageLayout>
    <Section>
      <Block>
        <HeaderRow goBackBtn>About PGP-UK</HeaderRow>
        <PageText>
          PGP-UK is part of the global network of Personal Genome Projects,
          which all share the vision of advancing science through open data
          sharing. Currently, there are projects in America, Austria, Canada,
          China and the UK. There are multiple ways to join the PGP-UK community
          and keep up to date with the project - just follow the links at the
          bottom of this page.
          {'\n\n'}
          We look forward to doing great science with you!
          {'\n\n'}
          The PGP-UK Team
        </PageText>
        <WorldImage />
        <PageText style={styles.disclaimer}>
          DISCLAIMER: The generation of genomic data is not an error-free
          process and our analysis software is under continued development. All
          information in this app was generated by PGP-UK and is not clinically
          approved. It is provided for personal and research purposes only. As
          the current knowledge of genetic and epigenetic variants has many
          uncertainties, we cannot guarantee that our analyses are either
          accurate or complete. {'\n\n'}
          To the extent possible under law, PGP-UK has waived all copyright and
          related or neighbouring rights to PGP. This work is published from the
          United Kingdom.
        </PageText>
        <PageText style={styles.bottom_text}>
          This app was designed and developed by the{' '}
          <PageText
            style={[styles.bottom_text, styles.link]}
            onPress={() =>
              Linking.openURL('https://www.personalgenomes.org.uk/team')
            }>
            PGP-UK/GenoME team.
          </PageText>
        </PageText>
        <SocialMedia />
      </Block>
    </Section>
  </PageLayout>
);

const WorldImage = () => (
  <FastImage
    source={require('./../../../assets/About/more-information_globe.png')}
    style={[
      {
        width: useSafeAreaFrame().width - 30,
        height: useSafeAreaFrame().width * 0.35,
      },
      styles.image,
    ]}
  />
);

const styles = StyleSheet.create({
  image: {
    margin: 0,
    marginTop: 20,
    marginBottom: 20,
  },
  disclaimer: {
    color: '#ff0000',
  },
  bottom_text: {
    marginTop: 20,
    marginBottom: 20,
  },
  link: {
    color: '#63BEE1',
  },
});

export default About;
